#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_EXPORT                              101
#define IDD_INFORMATION                         103
#define IDR_MENU_POPUP                          105
#define IDC_COMPONENT_LIST                      1000
#define IDC_IMAGE_GENERATION_MIPMAPS            1001
#define IDC_SCENE                               1002
#define IDC_PREPEND_RENAMING                    1003
#define IDC_PACKAGE                             1004
#define IDC_OPTIMIZATION_EPSILON                1005
#define IDC_FULL_SKELETAL                       1007
#define IDC_PROGRESS                            1030
#define IDC_FIXED_FUNCTION                      1036
#define IDC_PROGRAMMABLE                        1037
#define IDM_TRACING                             40000
#define IDS_VERSION                             40000
#define IDM_VIEWS                               40001
#define IDM_REFRESH                             40002
#define IDC_LIST_LODS                           40016
#define IDC_CMD_ADD_LOD                         40019
#define IDC_CMD_CLEAR_LOD                       40020
#define IDC_CMD_DELETE_LOD                      40021
#define IDC_LOD_REDUCTION                       40028
#define IDC_LOD_VALUE1                          40030
#define IDC_LOD_VALUE2                          40031
#define IDC_LOD_REDUCTION_SPIN                  40039
#define IDC_IMAGE_MAX_SIZE                      40046
#define IDC_IMAGE_POWER_OF_TWO                  40047
#define IDC_SKELETON_MAX_BONES                  40050
#define IDC_SKELETON_MAX_BONES_SPIN             40051
#define IDC_EXPORT_DIRECTORY                    40063
#define IDC_EXPORT_DIRECTORY_BROWSER            40067
#define IDC_ORIGINAL                            41000
#define IDC_PNG                                 41001
#define IDC_TGA                                 41002
#define IDC_DXTC                                41003
#define IDC_ETC1                                41004
#define IDC_ETC2                                41005
#define IDC_PVRTC2_4BPP                         41006
#define IDC_QUALITY_LOW                         42000
#define IDC_QUALITY_NORMAL                      42001
#define IDC_QUALITY_HIGH                        42002
#define IDC_DOT_SCENE_UTF8                      42004
#define IDC_INFORMATION                         42008
#define IDC_IMAGE_SCALE                         42021
#define IDC_BILINEAR                            42028
#define IDC_TRILINEAR                           42029
#define IDC_ANISOTROPIC_8                       42030
#define IDC_ANISOTROPIC_16                      42031
#define IDC_PHYSX                               42032
#define IDC_GEOMETRY                            42033
#define IDC_CAMERA                              42034
#define IDC_HELPER                              42035
#define IDC_SPLINE                              42036
#define IDC_TARGET                              42037
#define IDC_LIGHT                               42042
#define IDC_APEX                                42045
